services:
  db:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=task_user
      - POSTGRES_PASSWORD=task_pass
      - POSTGRES_DB=todo_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app  # mount local dir to docker
      - /app/.venv  # isolate local venv from docker
    command:
      - "python"
      - "src/manage.py"
      - "runserver"
      - "0.0.0.0:8000"
    environment:
      - ENVIRONMENT=local
      - DATABASE_URL=postgres://task_user:task_pass@db:5432/todo_app
      - SECRET_KEY=AIP0mAKfBEm8nDyDmzGJE2I7cLC54m89B4wSInj6ZVy3AEe0nMRJSY8oDcl23Eqx
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      - db

volumes:
  postgres_data:
